### PR TITLE
OBS Lite (WIP)

### PR DESCRIPTION
**Pull request by opatut**
This is where I'm working on the PCB for the "OpenBikeSensor Lite".

Here is my (preliminary) todos:

* [x] Basic schematic for sensors
* [x] Basic PCB
* [x] I2C Extension Port
* [x] Order PCBs and build test board for dimensioning of case
* [ ] Try out test board electrically
* [ ] Fix issues in test board
  - [x] GND/VCC on same fill area :joy:
  - [x] THT pads too small for easy soldering
  - [ ] ... TBD ...
* [ ] Decide how to add the button and add it to the board
* [ ] 2nd round PCB order and testing, fit setup into designed case

### CODE REVIEW

**Comment by opatut** [comment]
# v0.1.0

image

I did a little oupsie here and enabled 3V3 and GND on the same fill area. I think in old KiCAD versions checking one net would uncheck the other, and now it doesn't anymore (no idea why), so I had to cut a lot of ~~traces~~ *thermal relief spikes* in order to get the test boards to work.

Also, the pads were a bit small for my taste, so in order for beginners to be able to solder this, I'd make them a lot bigger.

# v0.1.1

Here is the revised version, maybe I'll add the button before I order again. This board is also smaller, as we don't need any space around it.

image 
image

**Comment by opatut** [comment]
Still working on 0.1.1, haven't ordered it yet ;)

image

What do you think? Feedback welcome.

**Comment by gluap** [comment]
@amandel suggested pulling the pin used on the current obs for battery voltage low to enable easy differentiation between the two boards in case we go for a unified firmware in the future.

To the same end using the same pins for the sensors and button could be beneficial. (will check).

**Comment by gluap** [comment]
@amandel suggested pulling the pin used on the current obs for battery voltage measurement low to enable easy differentiation between the two boards in case we go for a unified firmware in the future.

To the same end using the same pins for the sensors and button as on the current obs could be beneficial (but not strictly necessary) (will fetch laptop to check if that is the case already).  edit: will need to postpone to tomorrow - still buster on that laptop and kicad 5 does not open the new design.

**Comment by pReya** [comment]
@opatut I assume you've talked about this concept in meetings multiple times, but I'm not up to speed. Could you add a high level description of the motivation/feature set behind this board? Just trying to understand the differences to the regular OBS, without digging through schematics :D

**Comment by opatut** [comment]
> @amandel suggested pulling the pin used on the current obs for battery voltage measurement low to enable easy differentiation between the two boards in case we go for a unified firmware in the future.

I think I did that in 440a10e3c2cb1a68b2fbca8fe69cf4d54fe55610. See IO34 top left. I also changed my whole pinout to be identical to the OBS.

image

And here's the old one:

image

@pReya: This board is a huge simplification. It removes everything except the ESP32, Button and 2 Sensors. It utilizes sensor boards with the actual sensors mounted on the PCB instead of via coax cable. The idea is to attach it via a USB-OTG cable to a smartphone (Android) and use [serial USB](https://github.com/mik3y/usb-serial-for-android/) to read out the distance data and button presses. Combined with a suitable app, this is a low-cost (~15€), low-barrier (only solder ~20 THT pins) entry to OBS data collection, though not as suitable for device lending ("here's a device, just press the button, thanks for measuring for us") scenarios. Here's the current hardware design, next up we need a case :)

image

**Pull request merged**
